"""phase7_tenant_settings_and_contact_position

Revision ID: 186b18e906a5
Revises: 9a5c1c764b56
Create Date: 2026-07-03 08:52:31.789399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186b18e906a5'
down_revision: Union[str, None] = '9a5c1c764b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_profile', sa.Column('contact_position', sa.String(length=100), nullable=True))
    op.add_column('tenant', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'settings')
    op.drop_column('enterprise_profile', 'contact_position')
    # ### end Alembic commands ###
