"""add message_id replied_at to send_logs, replied_count to email_campaigns

Revision ID: 4191c6f1fa78
Revises: 9af0b1606155
Create Date: 2026-07-24 10:00:52.745048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4191c6f1fa78'
down_revision: Union[str, None] = '9af0b1606155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # replied_count: 先加为 nullable，填充默认值后再 NOT NULL
    op.add_column('email_campaigns', sa.Column('replied_count', sa.Integer(), nullable=True, server_default='0'))
    op.execute("UPDATE email_campaigns SET replied_count = 0 WHERE replied_count IS NULL")
    op.alter_column('email_campaigns', 'replied_count', nullable=False)
    op.add_column('send_logs', sa.Column('message_id', sa.String(length=500), nullable=True))
    op.add_column('send_logs', sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('send_logs', 'replied_at')
    op.drop_column('send_logs', 'message_id')
    op.drop_column('email_campaigns', 'replied_count')
    # ### end Alembic commands ###
