"""v1.2 enterprise expansion and product images

Revision ID: 779370b0cfe1
Revises: 186b18e906a5
Create Date: 2026-07-17 10:26:26.064016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '779370b0cfe1'
down_revision: Union[str, None] = '186b18e906a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprise_profile', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('enterprise_profile', sa.Column('employee_count', sa.String(length=50), nullable=True))
    op.add_column('enterprise_profile', sa.Column('factory_area', sa.String(length=100), nullable=True))
    op.add_column('enterprise_profile', sa.Column('annual_export_volume', sa.String(length=100), nullable=True))
    op.add_column('enterprise_profile', sa.Column('main_markets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('enterprise_profile', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('enterprise_profile', sa.Column('oem_odm', sa.String(length=255), nullable=True))
    op.add_column('enterprise_profile', sa.Column('company_advantages', sa.Text(), nullable=True))
    op.add_column('enterprise_profile', sa.Column('factory_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('enterprise_profile', sa.Column('certificate_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'images')
    op.drop_column('enterprise_profile', 'certificate_photos')
    op.drop_column('enterprise_profile', 'factory_photos')
    op.drop_column('enterprise_profile', 'company_advantages')
    op.drop_column('enterprise_profile', 'oem_odm')
    op.drop_column('enterprise_profile', 'certifications')
    op.drop_column('enterprise_profile', 'main_markets')
    op.drop_column('enterprise_profile', 'annual_export_volume')
    op.drop_column('enterprise_profile', 'factory_area')
    op.drop_column('enterprise_profile', 'employee_count')
    op.drop_column('enterprise_profile', 'year_established')
    # ### end Alembic commands ###
