"""add_language_and_foreign_body_to_email_templates

Revision ID: a4db44e6b0ff
Revises: 4191c6f1fa78
Create Date: 2026-07-24 14:53:26.359117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4db44e6b0ff'
down_revision: Union[str, None] = '4191c6f1fa78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('body_html_foreign', sa.Text(), nullable=True))
    op.add_column('email_templates', sa.Column('body_text_foreign', sa.Text(), nullable=True))
    op.add_column('email_templates', sa.Column('language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'language')
    op.drop_column('email_templates', 'body_text_foreign')
    op.drop_column('email_templates', 'body_html_foreign')
    # ### end Alembic commands ###
