"""phase5_enrichment

Revision ID: b7f052593465
Revises: 16fd5d17dd57
Create Date: 2026-07-01 14:31:26.865417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f052593465'
down_revision: Union[str, None] = '16fd5d17dd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('enrichment_status', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('enrichment_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_customers_enrichment_status'), 'customers', ['enrichment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_enrichment_status'), table_name='customers')
    op.drop_column('customers', 'enrichment_count')
    op.drop_column('customers', 'last_enriched_at')
    op.drop_column('customers', 'enrichment_status')
    # ### end Alembic commands ###
